baseUrl = "https://njudii.github.io/blog/"
title = "DII的博客"
lanuageCode = 'zh-cn'
disablePathToLower = true
theme = "maupassant"


[author]
  name = "DII的学生"
  github = "https://github.com/njudii/blog/"

[params]
  author = "DII的学生"
  subtitle = "南大匡院学习分享平台"
  busuanzi = true
  localSearch = true
  [[params.links]]
    title = "物院留学分享平台"
    name = "物院留学分享平台"
    url = "https://jialanxin.github.io/njuphy-/"
  [[params.links]]
    title = "软件教学系列"
    name = "软件教学系列"
    url = "https://itxia.github.io/soft/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 5

[permalinks]
  #post = "/:year/:month/:day/:filename/"
  post = "/post/:filename/"

[markup]
  [markup.highlight]
    lineNos = true
    style = "monokai"
